classDiagram
    class Webservice {
        + getUserByCredentials(String username, String password): User / None
        + getChildByUsername(String username): Child / None
        + getTapByChild(int child_id, int tap_id): Tap / None
        + getAllTaps(int child_id): Tap[]
    }

    class DAOUser {
        + User[] Users
        + getUserByCredentials(String username, String password): dict / None
    }

    class User {
        + String username
        + String email
        + String password
    }

    class DAOChild {
        + Child[] Children
        + getChildByUsername(String username): dict / None
        + getTapById(int child_id, int tap_id): dict / None
        + getAllTaps(int child_id): list
    }

    class Child {
        + int child_id
        + String child_name
        + String state
        + Tap last_tap
    }

    class Tap {
        + int id
        + int sleep_total
        + int time_slept
        + int time_remaining
        + Date start_date
        + Date end_date
    }

    Webservice -- DAOUser
    DAOUser -- User
    DAOUser -- Webservice
    Webservice -- DAOChild
    DAOChild -- Child 
    DAOChild -- Webservice
    DAOChild -- Tap