graph TD
    subgraph Frontend
        A[ConsoleView] --> B[APIClient]
        B -->|GET /getuser| C[Backend]
        B -->|GET /getchildren| C
    end

    subgraph Backend
        C[Flask Server] --> D[UserDAO]
        C --> E[ChildDAO]
        D --> F[Base de Dades]
        E --> F
    end

    subgraph Base de Dades
        F[Base de Dades] --> G[Taula User]
        F --> H[Taula Child]
        F --> I[Taula Tap]
        F --> J[Taula Role]
        F --> K[Taula Status]
        F --> L[Taula Treatment]
    end