graph TD
    subgraph Frontend
        A[ConsoleView] --> B[APIClient]
        B -->|GET /getuser| C[Backend]
        B -->|GET /getchildren| C
    end

    subgraph Backend
        C[Flask Server] --> D[UserDAO]
        C --> E[ChildDAO]
        D --> F[Base de Dades]
        E --> F
    end

