classDiagram

class User{
    -int id
    -String username
    -String password
    -String email
    +consultarInfants(): void
    +iniciarSessio(): boolean
}

class Child{
    -int id
    -String name
    -int sleep_average
        
    +consultarTractament: Treatment
    +consultarTap: array(Tap)
}

class Treatment{
    -int id
    -String name
}

class Tap{
    -int id
    -int status
    -datetime init 
    -datetime end 
}

Usuari "" --> "0-N" Child
Child "" --> "1-1" Treatment
Child "" --> "0-N" Tap
