flowchart TD
    A[Inici - Pantalla de benvinguda] --> B[Inici de sessió]
    B -->|Usuari no registrat| C[Pàgina de registre]
    B -->|Va oblidar la contrasenya| D[Recuperar contrasenya]
    B --> E[Pantalla principal]
    E -->|Si teniu més d'un nen a càrrec| F[Llistat de nens]
    F --> G[Menú del nen]
    E --> G
    E --> H[Configuració de l'usuari]
    E --> I[Informació de l'usuari]
    C -->|Usuari registrat| B
    D -->|Contrasenya restablida| B
    G --> J[Detalls del nen]
    G --> K[Configuració del nen]