flowchart TD
    A[Inici - Benvinguda] --> B[Login]
    A --> C[Registre]
    B -->|Credencials correctes| D[Dashboard]
    B -->|Credencials incorrectes| E[Error de Login]
    C --> B
    D --> F[Pàgina de Cerca]
    D --> G[Perfil d'Usuari]
    F --> H[Detall de Tapa]
    G --> B[Logout]

    %% Informació d'Entrada i Vista
    classDef entrada fill
    classDef vista fill

    class A,C entrada
    class B,E vista
    class D,F,G vista

