flowchart TD
    Inicio[Inici] --> MenuPrincipal[Menu Principal]
    MenuPrincipal --> Categorias[Categorías]
    MenuPrincipal --> Buscar[Buscar]
    MenuPrincipal --> Perfil[Perfil d'usuari]

    Categorias --> Ropa[Ropa]
    Categorias --> Electronica[Electrònica]
    Categorias --> Hogar[Hogar]

    Ropa --> DetalleProductoRopa[Detall de Producte]
    Electronica --> DetalleProductoElectronica[Detall de Producte]
    Hogar --> DetalleProductoHogar[Detall de Producte]

    Buscar --> Resultados[Resultats de la cerca]
    Resultados --> DetalleProducto[Detall de Producte]

    Perfil --> VerPerfil[Veure Perfil]
    Perfil --> EditarPerfil[Editar Perfil]
    Perfil --> Logout[Tancar Sessió]

    DetalleProducto --> AñadirCarrito[Afegeix a la cistella]
    DetalleProducto --> Comprar[Comprar ara]
    DetalleProducto --> ContinuarCompra[Continuar la compra]
