flowchart TD
    A[<b>Client View</b> <br> Input username] -->|Envia dades username| B[Client DAO User<br> getUserByUsername]
    B -->|Petición HTTP  GET username| C[<b>Servidor</b> <br> Webservice]
    C -->|Consulta DAOUser | D[Server DAO User <br> getUserByUsername]
    D -->|Respon Objecte User if exists| C
    C -->|Reposta HTTP amb Json User if exists| B
    B -->|Dades processades| F[<b>Client View</b> <br> Show Info User if exists]
