flowchart TD
    A["Home - Welcome Screen"] --> B["Login"] --> G
    B -- Unregistered user --> C["Registration Page"]
    B -- Forgot password --> D["Recover Password"]
    B -->|If you have more than one dependent child| F[List of children]
    F --> G["Child Menu"]
    C -- Registered user --> B
    D -- Password reset --> B
    G --> J["Child Details"] & K["Child Settings"]
    J --> L["Patch Status"]